In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/student_performance_exploration_v2 - student_performance_exploration_v2.csv')

In [ ]:
df

,student_id,department,gender,study_hours_per_week,attendance_percentage,sleep_hours_per_night,commute_time_minutes,internet_access,class_participation,previous_academic_result,assignment_score,midterm_score,final_exam_score,total_score,passed_course
0,STU001,EEE,Female,15.0,81.0,8.0,22,Sometimes unreliable,High,Average,70.0,56,73,66,Yes
1,STU002,CSE,Male,20.0,78.0,8.0,40,Reliable,Low,Good,72.0,63,75,70,Yes
2,STU003,BBA,Male,22.0,59.0,6.0,53,Reliable,Medium,Good,67.0,68,82,74,Yes
3,STU004,CSE,Female,5.0,73.0,6.0,14,Reliable,Medium,Good,62.0,63,53,58,Yes
4,STU005,BBA,Female,13.0,80.0,7.0,54,Limited,Low,Good,51.0,43,45,46,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,STU096,EEE,Male,10.0,84.0,9.0,35,Reliable,Low,Good,73.0,38,50,50,Yes
96,STU097,English,Female,5.0,77.0,6.0,12,Sometimes unreliable,Medium,Needs support,42.0,26,21,27,No
97,STU098,CSE,Male,10.0,77.0,8.0,60,Limited,Medium,Needs support,32.0,37,51,42,No
98,STU099,BBA,Male,5.0,73.0,8.0,17,Reliable,Low,Needs support,41.0,19,10,19,No
99,STU100,EEE,Male,17.0,89.0,7.0,28,Sometimes unreliable,High,Excellent,81.0,70,65,70,Yes

In [ ]:
df.shape

(100, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   student_id                100 non-null    object
 1   department                100 non-null    object
 2   gender                    100 non-null    object
 3   study_hours_per_week      98 non-null     float64
 4   attendance_percentage     98 non-null     float64
 5   sleep_hours_per_night     99 non-null     float64
 6   commute_time_minutes      100 non-null    int64
 7   internet_access           100 non-null    object
 8   class_participation       100 non-null    object
 9   previous_academic_result  100 non-null    object
 10  assignment_score          99 non-null     float64
 11  midterm_score             100 non-null    int64
 12  final_exam_score          100 non-null    int64
 13  total_score               100 non-null    int64
 14  passed_course             100 non-null    object
dtypes: float64(4), int64(4), object(7)
memory usage: 11.8+ KB

In [ ]:
df.describe()

,study_hours_per_week,attendance_percentage,sleep_hours_per_night,commute_time_minutes,assignment_score,midterm_score,final_exam_score,total_score
count,98.000000,98.000000,99.000000,100.000000,99.000000,100.000000,100.000000,100.000000
mean,10.897959,76.071429,7.191919,34.380000,57.616162,53.400000,54.580000,54.800000
std,4.759125,11.274687,1.065955,17.510043,13.145735,14.119977,12.891294,11.004131
min,1.000000,49.000000,4.000000,5.000000,32.000000,19.000000,10.000000,19.000000
25%,8.000000,69.250000,6.500000,20.500000,46.000000,42.750000,48.000000,48.000000
50%,11.000000,77.000000,7.000000,33.000000,57.000000,53.500000,55.000000,56.000000
75%,14.000000,84.000000,8.000000,49.250000,67.000000,63.000000,63.250000,63.000000
max,22.000000,100.000000,9.000000,70.000000,92.000000,87.000000,92.000000,78.000000

In [ ]:
df.columns

Index(['student_id', 'department', 'gender', 'study_hours_per_week',
       'attendance_percentage', 'sleep_hours_per_night',
       'commute_time_minutes', 'internet_access', 'class_participation',
       'previous_academic_result', 'assignment_score', 'midterm_score',
       'final_exam_score', 'total_score', 'passed_course'],
      dtype='object')

In [ ]:
df.isnull().sum().sum()

np.int64(6)

In [ ]:
df.isnull().sum()

student_id                  0
department                  0
gender                      0
study_hours_per_week        2
attendance_percentage       2
sleep_hours_per_night       1
commute_time_minutes        0
internet_access             0
class_participation         0
previous_academic_result    0
assignment_score            1
midterm_score               0
final_exam_score            0
total_score                 0
passed_course               0
dtype: int64

In [ ]:
df.describe().loc[['mean', 'min', 'max']]

,study_hours_per_week,attendance_percentage,sleep_hours_per_night,commute_time_minutes,assignment_score,midterm_score,final_exam_score,total_score
mean,10.897959,76.071429,7.191919,34.38,57.616162,53.4,54.58,54.8
min,1.000000,49.000000,4.000000,5.00,32.000000,19.0,10.00,19.0
max,22.000000,100.000000,9.000000,70.00,92.000000,87.0,92.00,78.0

In [ ]:
df.select_dtypes(include="number").columns

Index(['study_hours_per_week', 'attendance_percentage',
       'sleep_hours_per_night', 'commute_time_minutes', 'assignment_score',
       'midterm_score', 'final_exam_score', 'total_score'],
      dtype='object')

In [ ]:
df.isnull()

,student_id,department,gender,study_hours_per_week,attendance_percentage,sleep_hours_per_night,commute_time_minutes,internet_access,class_participation,previous_academic_result,assignment_score,midterm_score,final_exam_score,total_score,passed_course
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
 df.dropna().head(10)

,student_id,department,gender,study_hours_per_week,attendance_percentage,sleep_hours_per_night,commute_time_minutes,internet_access,class_participation,previous_academic_result,assignment_score,midterm_score,final_exam_score,total_score,passed_course
0,STU001,EEE,Female,15.0,81.0,8.0,22,Sometimes unreliable,High,Average,70.0,56,73,66,Yes
1,STU002,CSE,Male,20.0,78.0,8.0,40,Reliable,Low,Good,72.0,63,75,70,Yes
2,STU003,BBA,Male,22.0,59.0,6.0,53,Reliable,Medium,Good,67.0,68,82,74,Yes
3,STU004,CSE,Female,5.0,73.0,6.0,14,Reliable,Medium,Good,62.0,63,53,58,Yes
4,STU005,BBA,Female,13.0,80.0,7.0,54,Limited,Low,Good,51.0,43,45,46,No
5,STU006,EEE,Female,1.0,76.0,7.0,26,Limited,Medium,Average,41.0,38,50,44,No
6,STU007,CSE,Male,5.0,94.0,7.0,33,Reliable,Low,Needs support,41.0,50,43,45,No
8,STU009,CSE,Female,14.0,71.0,9.0,11,Sometimes unreliable,High,Good,78.0,39,69,60,Yes
9,STU010,EEE,Female,9.0,82.0,8.0,32,Reliable,Medium,Needs support,55.0,70,42,54,Yes
10,STU011,CSE,Female,11.0,94.0,7.0,19,Reliable,Medium,Good,60.0,63,55,59,Yes